### ISSUE TITLE
Better Longcode Phone Number Management via Twilio API integration

### ISSUE THREAD

**Issue by deasterdaywfp** [WorkingFamilies/Spoke_legacy#85]
Need help setting up a better in-app or command line system to buy and release longcodes in bulk for use in WF Spoke. Currently this is an incredibly arduous process - especially to release and is therefore leading to more expense from our projects than is really needed. @codygordon @ariKamen -- would love to know if this is something that we can spend a little development time to set up soon.

**Comment by joemcl** [comment]
Hey @schuyler1d didn't MoveOn create something like this? @deasterdaywfp see this - https://github.com/MoveOnOrg/switchboard-twilio

**Comment by joemcl** [comment]
Hey @deasterdaywfp so if you're happy with switchboard-twilio, let's close this Issue.
